<?php
// @codingStandardsIgnoreFile
?>
<?php
$helper = $this->helper('Magento\Search\Helper\Data');
$wyoHelper = $this->helper('Wyomind\Elasticsearch\Helper\Data');
$taxHelper = $this->helper('Wyomind\Elasticsearch\Helper\Tax');
$autocompleteHelper = $this->helper('Wyomind\Elasticsearch\Helper\Autocomplete');
?>
<div id="header-search" class="skip-content skip-content--style">
    <div class="search-wrapper block block-search">
        <div class="block block-title"><strong><?php /* @escapeNotVerified */ echo __('Search'); ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form" action="<?php /* @escapeNotVerified */ echo $helper->getResultUrl() ?>" method="get">
                <div class="field search">
                    <?php /* <label class="label" for="search" data-role="minisearch-label">
                        <span><?php echo __('Search'); ?></span>
                    </label> */ ?>
                    <div class="control">
                        <input id="search"
                               data-mage-init='{"wyoSearch":{
                                    "formSelector":"#search_mini_form",
                                    "url":"<?php /* @escapeNotVerified */ echo $wyoHelper->getAutocompleteUrl(); ?>",
                                    "destinationSelector":"#search_autocomplete"}
                               }'
                               type="text"
                               name="<?php /* @escapeNotVerified */ echo $helper->getQueryParamName() ?>"
                               value="<?php /* @escapeNotVerified */ echo $helper->getEscapedQueryText() ?>"
                               placeholder="<?php /* @escapeNotVerified */ echo __('Search'); ?>"
                               class="input-text"
                               maxlength="<?php /* @escapeNotVerified */ echo $helper->getMaxQueryLength();?>"
                               role="combobox"
                               aria-haspopup="false"
                               aria-autocomplete="both"
                               autocomplete="off"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?php echo $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions">
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Search')) ?>"
                            class="action search">
                        <span><?php /* @escapeNotVerified */ echo __('Search'); ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div> <!-- end: search-wrapper -->
</div>

<script>
    require(['underscore', 'Magento_Catalog/js/price-utils'], function (_, utils) {
        _.mixin({
            getBaseUrl: function () {
                return '<?php echo $block->getBaseUrl() ?>';
            },
            getFormattedPrice: function (price, productTaxClassId) {
                return _.formatPrice(_.calculateTax(_.convertPrice(price), productTaxClassId));
            },
            formatPrice: function (price) {
                var priceFormat = <?php /* @escapeNotVerified */ echo $this->helper('Magento\Tax\Helper\Data')->getPriceFormat($block->getStore()); ?>;

                return utils.formatPrice(price, priceFormat);
            },
            calculateTax: function (price, productTaxClassId) {
                var needPriceConversion = <?php echo $taxHelper->needPriceConversion() ? 'true' : 'false' ?>;
                var taxRates = <?php /* @escapeNotVerified */ echo json_encode($taxHelper->getRates()) ?>;

                if (!needPriceConversion || !taxRates[productTaxClassId]) {
                    return price;
                }

                var rate = taxRates[productTaxClassId] / 100;
                var priceIncludesTax = <?php echo $taxHelper->priceIncludesTax() ? 'true' : 'false' ?>;

                if (priceIncludesTax) {
                    return price / (1 + rate);
                }

                return price + price * rate;
            },
            convertPrice: function (price) {
                var rate = <?php echo $wyoHelper->getCurrentCurrencyRate() ?>;

                return price * rate;
            }
        });
    });
</script>
<script id="wyomind-tmpl-no-result" type="text/x-magento-template">
    <?php echo $autocompleteHelper->getNoResultTemplate() ?>
</script>
<script id="wyomind-tmpl-product" type="text/x-magento-template">
    <?php echo $autocompleteHelper->getTemplate('product') ?>
</script>
<script id="wyomind-tmpl-category" type="text/x-magento-template">
    <?php echo $autocompleteHelper->getTemplate('category') ?>
</script>
<script id="wyomind-tmpl-cms" type="text/x-magento-template">
    <?php echo $autocompleteHelper->getTemplate('cms') ?>
</script>
